#!/usr/bin/env sh

#
#	MetaCall Distributable by Parra Studios
#	Distributable infrastructure for MetaCall.
#
#	Copyright (C) 2016 - 2019 Vicente Eduardo Ferrer Garcia <vic798@gmail.com>
#
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#
#		http://www.apache.org/licenses/LICENSE-2.0
#
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#

# Help command
help() {
	echo
	echo "Usage:"
	echo
	echo "`basename $0` source rpath interpreter"
	echo "  source: folder where libs are located"
	echo "  rpath: new rpath to modify in the libs from source"
	echo "  interpreter: path to where the interpreter ld-linux is located"
	echo
	echo "Example:"
	echo
	echo "  `basename $0` /home/root/python/lib /home/root/python/lib:/home/root/libc/lib /home/root/libc/lib"
	echo
}


main() {
	# Check if source folder is defined
	if [ -z ${1+x} ]; then
		echo "Error: Source folder is not defined."
		help
		exit 1
	fi

	# Check if source folder exists
	if [ ! -d "${1}" ]; then
		echo "Error: Source folder does not exist."
		help
		exit 1
	fi

	# Check if rpath is defined
	if [ -z ${2+x} ]; then
		echo "Error: Rpath is not defined."
		help
		exit 1
	fi

	# Check if interpreter is defined
	if [ -z ${3+x} ]; then
		echo "Error: Interpreter is not defined."
		help
		exit 1
	fi

	# Define variable alias
	source=${1}
	rpath=${2}
	interpreter=`ls -la ${3}/ld-linux* | awk '{ print $9 }'`

	# Retrieve all ELF files
	ELFS=`find ${source} -type f -print0 | xargs -0 -n 10 file -i | grep -E "application\/x-sharedlib|application\/x-executable" | awk '{ print $1 }' | sed 's/://'`

	# Iterate through elf list
	for elf in ${ELFS}; do
		patchelf --set-rpath ${rpath} ${elf}
		patchelf --set-interpreter ${interpreter} ${elf}
		patchelf --shrink-rpath ${elf}

		# Show new locations
		echo "${elf} -> ${rpath} | ${interpreter}"
	done
}

main "$@"

exit 0
